# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChartView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChartView
pod 'LookinServer', :configurations => ['Debug']

  target 'ChartViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChartViewUITests' do
    # Pods for testing
  end

end
